version: 0.4.6

namespace: url-shortener
project: service

services:
  - name: web
    image: ghcr.io/markmorcos/url-shortener
    port: 3000
    env:
      - name: BASE_URL
        value: https://rdr.cx
      - name: REDIS_URL
        valueFrom:
          secretKeyRef:
            name: redis-secret
            key: REDIS_URL
    ingress:
      host: rdr.cx
      path: /?(.*)
      pathType: ImplementationSpecific
